# Generated by Django 4.1.1 on 2022-10-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
